apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-joke-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-joke-api
  template:
    metadata:
      labels:
        app: random-joke-api
    spec:
      containers:
        - name: random-joke-api
          image: malavyaraval/random-joke-api:latest
          ports:
            - containerPort: 3000
